kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "${PVC_CLAIM_NAME}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "${PV_NAME}"
  storageClassName: azureblob-nfs-premium