apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: suskumtestpvcnew1
    volumeAttributes:
      resourceGroup: suskuma-nifi-02
      storageAccount: suskumateststr1
      containerName: custom-vision-model-v2
      protocol: nfs
