kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-blob-1
  storageClassName: azureblob-nfs-premium
